#!/system/bin/bash
# for use on Android
# lets me actually use Sony's camera

# Exit if not on Android
if uname -a | grep Android > /dev/null; then
  true
else
  echo "This script is for Android."
fi

echo "Tidying up photos in DCIM/100ANDRO and moving them to DCIM/Camera..."
echo --------
for file in /sdcard/DCIM/100ANDRO/DSC*; do
  mv -n "$file" "/sdcard/DCIM/Camera/IMG_$(date -r "$file" +"%Y%m%d_%H%M%S").jpg"
done
echo --------

echo "Tidying up videos in DCIM/100ANDRO and moving them to DCIM/Camera..."
echo --------
for file in /sdcard/DCIM/100ANDRO/MOV_*; do
  mv -n "$file" "/sdcard/DCIM/Camera/VID_$(date -r "$file" +"%Y%m%d_%H%M%S").mp4"
done
echo --------
echo
echo Done.
