#!/bin/bash
# for use on Android
# lets me actually use Sony's camera

# Exit if not on Android
if ! uname -a | grep -qs Android; then
  echo "This script is for Android. Exiting"
  exit 1
fi

if ls /sdcard/DCIM/100ANDRO/DSC_* &> /dev/null; then
  echo "Tidying up photos in DCIM/100ANDRO and moving them to DCIM/Camera..."
  for file in /sdcard/DCIM/100ANDRO/DSC*; do
    mv -n "$file" "/sdcard/DCIM/Camera/IMG_$(date -r "$file" +"%Y%m%d_%H%M%S").jpg"
  done
else
  echo "There are no photos (DSC_*) in DCIM/100ANDRO. Skipping"
fi

if ls /sdcard/DCIM/100ANDRO/MOV_* &> /dev/null; then
  echo "Tidying up videos in DCIM/100ANDRO and moving them to DCIM/Camera..."
  for file in /sdcard/DCIM/100ANDRO/MOV_*; do
    mv -n "$file" "/sdcard/DCIM/Camera/VID_$(date -r "$file" +"%Y%m%d_%H%M%S").mp4"
  done
else
  echo "There are no videos (MOV_*) in DCIM/100ANDRO. Skipping"
fi

echo
echo Done.

