#!/bin/bash
# Sends input to xclip

# Read stdin if no argument given
if [[ -z ${1+x} ]];then
  string=$(cat)
else
  string="$@"
fi
echo "$string" | xclip -r -sel clip
echo "$string" | xclip -r -sel prim
