#!/usr/bin/env racket
#lang racket
; vim: filetype=racket
(require threading
         json)

;; (define (parse-output output)
;;   (string-split output "\n"))

;; jsexpr: jsnull | boolean | string | (or exact-integer inexact-real)
;;                | (listof jsexpr) | (and hash-eq (hash symbol? jsexpr?))
(define (parse-output/json output)
  (~> (string-split output "\n")
      (map (λ (x) (string-split x "\t")) _) ; '(("3" "./file") ("10" "./file2"))
      (map (λ (x) (hasheq 'size (first x)
                          'name (second x)))
           _)
      jsexpr->string
      displayln))

(~> (with-output-to-string
        (λ () (system (string-append "du" " "
                                     (~> (current-command-line-arguments)
                                         vector->list
                                         string-join)))))
     parse-output/json)
