#!/bin/bash
# Switch to next fcitx input method in a currently hard coded array

current_im="$(qdbus org.fcitx.Fcitx /inputmethod org.fcitx.Fcitx.InputMethod.GetCurrentIM)"
# Parse fcitx config file to get im_list
im_list=($(grep 'EnabledIMList' ~/.config/fcitx/profile \
           | tr ',' '\n' \
           | grep 'True' \
           | sed 's/EnabledIMList=//' \
           | cut -d':' -f 1 \
           | sort \
           | tac))
#im_list=(fcitx-keyboard-us mozc rime hangul)
new_im=""

# accept $1 for setting direction
# $1: "next" or "prev"
case $1 in
    ("next")mode=next;;
    ("prev")mode=prev;;
    (*)mode=next;;
esac

# figure out which index the current im is, add one to it and wrap around as new im index
for i in $(seq 0 $(( ${#im_list[@]} - 1 )) ); do
  if [ "${im_list[$i]}" == "$current_im" ]; then
    case $mode in
        ("next")new_im=${im_list[ $(((i +1) % ${#im_list[@]})) ]};;
        ("prev")new_im=${im_list[$(lua -e "print(($i - 1) % ${#im_list[@]})")]};;
        (*)echo "mode should be next or prev";;
    esac
  fi
done

fcitx-remote -s "$new_im"
