#!/usr/bin/env racket
#lang racket
; vim: filetype=racket
(require threading
         json)

;; (define (write-output/sexp output)
;;   (~> (string-split output "\n")
;;       println))

;; jsexpr: jsnull | boolean | string | (or exact-integer inexact-real)
;;                | (listof jsexpr) | (and hash-eq (hash symbol? jsexpr?))
(define (write-output/json output)
  (~> (string-split output "\n")
      jsexpr->string
      displayln))

(~> (with-output-to-string
        (λ () (system (string-append "find" " "
                                     (~> (current-command-line-arguments)
                                         vector->list
                                         string-join)))))
    write-output/json)

