#!/usr/bin/env bash

mouse_location=$(xdotool getmouselocation)
x=$(echo "$mouse_location" | cut -d ' ' -f 1 | cut -d ':' -f 2)
y=$(echo "$mouse_location" | cut -d ' ' -f 2 | cut -d ':' -f 2)
get_pixel_color "$x" "$y"
