#!/bin/bash

echo install-kaku <direct download link>
cd /tmp
wget $1
sudo mv Kaku-linux* /opt/
sudo ln -sf /opt/Kaku-linux*/Kaku /usr/bin/Kaku
echo "
[Desktop Entry]
Name=Kaku
Comment=The next generation music client
Exec=/usr/bin/Kaku
Icon=Kaku
Type=Application
StartupNotify=true
Categories=AudioVideo;Player;
" > Kaku.desktop
sudo mv Kaku.desktop /usr/share/applications
