#!/bin/bash
helptext="

$0 <arguments>
 arguments:
  -s: sensitivity multiplier (default 950)
  -d: device name (default SIGMACHIP Usb Mouse)
  -h: show help (this)

"

if test -z "$1"; then
    echo "$helptext"
    exit 1
fi

sensitivity=2
device="SIGMACHIP Usb Mouse"

while getopts "cs:S:r:d:h?" opt; do
  case "$opt" in
    s)
        sensitivity="$OPTARG"
        ;;
    d)
        device="$OPTARG"
        ;;
    h|?)
        echo "$helptext"
        exit 0
        ;;
  esac
done

xinput set-prop "$device" "Coordinate Transformation Matrix" "$sensitivity" 0 0 0 "$sensitivity" 0 0 0 1
