#!/bin/bash
# pdf-optimize <infile> <outfile>
# optimize pdf with ghostscript
[ -z "$1" ] && exit 1
[ -z "$2" ] && exit 1
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile="$2" "$1"
