#!/bin/bash

print_help_and_exit () {
  echo "Usage: random-notifications <title txt file> [body text file] [icon path file] [line to print]"
  echo " A random line from each file will be picked and used to send notification"
  echo " unless the fourth argument is given, which would be used instead of a random number."
  echo " Use /dev/null for skipping a field."
  exit $1
}

if [[ $1 == "-h" || $1 == "--help" ]]; then
  print_help_and_exit 0
fi

if [[ -z ${1+x} ]]; then print_help_and_exit 1; else title_txt="$1"; fi
if [[ -z ${2+x} ]]; then body_txt="/dev/null"; else body_txt="$2"; fi
if [[ -z ${3+x} ]]; then iconpath_txt="/dev/null"; else iconpath_txt="$3"; fi

mapfile -t titlearray < "$title_txt" # title = summary
mapfile -t bodyarray < "$body_txt"
mapfile -t iconpatharray < "$iconpath_txt"
size=${#titlearray[@]}

if [[ -z ${4+x} ]]; then rand=$(( ( RANDOM % size )  + 1 )); else rand=$4; fi

#RED='\033[1;33m'
#PURPLE='\033[0;35m'
#NC='\033[0m' # No Color
#bold=$(tput bold)
#normal=$(tput sgr0)

# notify-send [OPTION...] <SUMMARY> [BODY] - create a notification
notify-send --icon="${iconpatharray[rand-1]}" "${titlearray[rand-1]}" "${bodyarray[rand-1]}"
