#!/bin/bash

print_help_and_exit () {
  echo "Usage: print-random-line <file> [line number]"
  exit $1
}

if [[ $1 == "-h" || $1 == "--help" ]]; then
  print_help_and_exit 0
fi

if [[ -z ${1+x} ]]; then print_help_and_exit 1; else file="$1"; fi
if [[ -s $file ]]; then true; else exit 0; fi

mapfile -t linearray < "$file" # title = summary
size=${#linearray[@]}

if [[ -z ${2+x} ]]; then rand=$(( ( RANDOM % size )  + 1 )); else rand=$2; fi

echo "${linearray[rand-1]}"
