#!/usr/bin/env racket
#lang racket
; vim: filetype=racket
; random-string [length]

(define charset (or (getenv "CHARSET")
                    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"))

(define (select-random-item lst #:ref-fn [ref-fn list-ref] #:length-fn [length-fn length])
  (ref-fn lst (random (length-fn lst))))

(define (random-string [len 16])
  (list->string
    (for/list ([i (in-range len)])
      (select-random-item charset #:ref-fn string-ref #:length-fn string-length))))

(if (empty? (vector->list (current-command-line-arguments)))
  (displayln (random-string))
  (displayln (random-string (string->number (vector-ref (current-command-line-arguments) 0)))))
