#!/bin/bash
# reencode_image <ext> <file>
# reencodes in place image with imagemagick convert
case "$1" in
    -h|--help)
        echo "$(basename "$0") <file>"
        echo "$(basename "$0") <ext> <file>"
        echo "reencodes image in place with imagemagick convert"
        exit 0
        ;;
    *)
        if [ -z "$2" ]; then
            src="$1"
            ext="${1##*.}"
        else
            ext="$1"
            src="$2"
        fi
esac

tmp=$(mktemp XXXX."$ext")
convert "$src" "$tmp"
mv "$tmp" "$src"
