#!/bin/bash

echoexit () {
    echo "
renri-normalize-breath-sound [path-to-renri] [level]
 Normalize Renri's breath sounds to <level> and make them available
 as 'nb1', 'nb2', 'nb3', and 'nb4'.

 Usage:
  path-to-renri: path to Renri's VB folder
  level: what level to normalize her breath sounds to, default -3db
"
    exit "$1"
}

{ [ -n "$1" ] && renri_path="$1"; } || echoexit 1
{ [ -n "$2" ] && level="$2"; } || level=-3db
renri_breath_path="$renri_path"/ブレス
renri_normalized_breath_path="$renri_path"/ブレス-normalized

echo "Copying original breath sounds..."
cp -rf "$renri_breath_path" "$renri_normalized_breath_path"

echo "Normalizing copied breath sounds..."
for i in "$renri_normalized_breath_path"/*.wav; do
    normalize -q --amplitude="$level" "$i"
done

echo "Changing UTAU alias for normalized breath sounds to nb[1234]..."
iconv -f shift-jis -t utf8 "$renri_normalized_breath_path"/oto.ini \
    | sed 's/- ブレス/nb/g' \
    | iconv -f utf8 -t shift-jis \
    | sponge "$renri_normalized_breath_path"/oto.ini

echo "Normalization complete."
