#!/bin/bash
# restart pulseaudio
# because gnome-control-center doesn't let me run bind keys to run commands in sequence
pulseaudio -k # PulseAudio restarts itself if killed this way
notify-send "PulseAudio has been restarted" " " --icon view-refresh
