#!/bin/bash
roio_command=$1
roio_full_command="$@"

if killall -q -e -0 $roio_command; then
  # killall -0 succeeded, roio_command running
  echo "$roio_command already running"
else
  # killall -0 did not succeed, roio_command not running
  $roio_full_command
fi
