#!/bin/bash
helptext="

$0 <arguments>
 arguments:
  -c: centered area?
  -s: sensitivity multiplier (default 950)
  -S: tablet sensitivity multiplier for calculating center area (default 950)
  -d: device name
  -r: area ratio (default 16:9)
  -h: show help (this)

"

if test -z "$1"; then
    echo "$helptext"
    exit 1
fi

centered=0
ratio=16:9
sensitivity=950
sensitivity_orig=950
device="Wacom Intuos PT S 2 Pen stylus"
offset=(0 0)

while getopts "cs:S:r:d:h?" opt; do
  case "$opt" in
    c)
        centered=1
        ;;
    s)
        sensitivity="$OPTARG"
        ;;
    S)
        sensitivity_orig="$OPTARG"
        ;;
    r)
        ratio="$OPTARG"
        ;;
    d)
        device="$OPTARG"
        ;;
    h|?)
        echo "$helptext"
        exit 0
        ;;
  esac
done

xd=$(echo "$ratio" | cut -d':' -f 1)
yd=$(echo "$ratio" | cut -d':' -f 2)

if test "$centered" == 1; then
    offset[0]=$(echo '(''('"$sensitivity_orig"*"$xd"')'-'('"$sensitivity"*"$xd"')'')'/2 | bc)
    offset[1]=$(echo '(''('"$sensitivity_orig"*"$yd"')'-'('"$sensitivity"*"$yd"')'')'/2 | bc)
fi

topleft_x=$(echo 0+"${offset[0]}" | bc)
topleft_y=$(echo 0+"${offset[1]}" | bc)
bottomright_x=$(echo '('"$sensitivity"*"$xd"')'+"${offset[0]}" | bc)
bottomright_y=$(echo '('"$sensitivity"*"$yd"')'+"${offset[1]}" | bc)

xsetwacom --set "$device" Area "$topleft_x" "$topleft_y" "$bottomright_x" "$bottomright_y"
